### ISSUE TITLE
`Format: Javascript` doesn't show up

### ISSUE THREAD

**Issue by jmagnusson** [jdc0589/JsFormat#117]
`Format: Javascript` doesn't show up in the ⌘-Shift-P menu unless syntax has been set to JavaScript. This is especially annoying if I haven't saved the file yet.

**Comment by FeBe95** [comment]
Any update? I also use the plugin mostly via the Command Palette and it would be great to see the "Format: Javascript" command also for plain text files

**Comment by titoBouzout** [comment]
Yes, every time I use this plugin is because:

1. Created new empty view
2. Paste JSON code
3. I look for "format: javascript" and is not there.
4. .I need to change the syntax.. 
5. Then I need to look again..

It would be nice to allow formatting if at least ... the text in the view starts with "{".. this will avoid.

**Comment by titoBouzout** [comment]
I created  /User/jsformat.py with content

import sublime_plugin

class JsFormat2Command(sublime_plugin.TextCommand):
    def run(self, edit):
        self.view.settings().set('syntax', 'Packages/Better JavaScript/JavaScript.tmLanguage')
        self.view.run_command('js_format')

then /User/Commands.sublime-commands with content 

[{
	"caption": "Format: Javascript",
	"command": "js_format2"
}]

**Comment by wuilliam321** [comment]
It was solved here: https://github.com/jdc0589/JsFormat/pull/140
